language: java

jdk:
 - oraclejdk8
 - oraclejdk9
 - openjdk8
 - openjdk9
 - openjdk10
 - openjdk11

script:
 - gradle test
 - gradle test jacocoTestReport

after_success:
 - bash <(curl -s https://codecov.io/bash)

before_script:
    - wget http://services.gradle.org/distributions/gradle-5.4-bin.zip
    - unzip gradle-5.4-bin.zip
    - export GRADLE_HOME=$PWD/gradle-5.4
    - export PATH=$GRADLE_HOME/bin:$PATH
